package com.ternbusty.takoyaki.cgroup;

import com.ternbusty.takoyaki.logger.Logger;
import com.ternbusty.takoyaki.spec.Spec;
import com.ternbusty.takoyaki.syscall.Constants;
import com.ternbusty.takoyaki.syscall.Libc;
import com.ternbusty.takoyaki.syscall.PosixIO;

import java.io.ByteArrayOutputStream;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.List;

/**
 * Attach an eBPF program of type BPF_PROG_TYPE_CGROUP_DEVICE to the container's
 * cgroup. The program enforces spec.linux.resources.devices.
 *
 * The generated bytecode iterates over the rule list. Each rule compares the
 * incoming (type, access, major, minor) tuple and short-circuits to return its
 * own allow/deny decision; non-matching rules fall through to the next.
 *
 * BPF input layout (from include/uapi/linux/bpf.h):
 *   struct bpf_cgroup_dev_ctx {
 *       __u32 access_type;   // (BPF_DEVCG_ACC_* << 16) | BPF_DEVCG_DEV_*
 *       __u32 major;
 *       __u32 minor;
 *   };
 *
 * Output: R0 = 1 to allow, 0 to deny.
 *
 * Reference: runc libcontainer/cgroups/devices/ebpf.go, youki crates/libcgroups
 * cgroup/v2/devices/bpf.rs. Our encoder is a simplified port.
 */
public final class DeviceCgroup {
    // bpf syscall numbers (same on aarch64 and x86_64 thanks to generic syscalls)
    private static final long NR_bpf_aarch64 = 280L;
    private static final long NR_bpf_x86_64  = 321L;

    private static final int BPF_PROG_LOAD   = 5;
    private static final int BPF_PROG_ATTACH = 8;

    private static final int BPF_PROG_TYPE_CGROUP_DEVICE = 15;
    private static final int BPF_CGROUP_DEVICE           = 6;

    // BPF instruction opcodes (subset)
    private static final int BPF_LDX_MEM_W  = 0x61; // BPF_LDX | BPF_MEM | BPF_W
    private static final int BPF_ALU_MOV_K  = 0xb7; // BPF_ALU64 | BPF_MOV | BPF_K
    private static final int BPF_ALU_MOV_X  = 0xbf; // BPF_ALU64 | BPF_MOV | BPF_X
    private static final int BPF_ALU_RSH_K  = 0x77; // BPF_ALU64 | BPF_RSH | BPF_K
    private static final int BPF_ALU_AND_K  = 0x57; // BPF_ALU64 | BPF_AND | BPF_K
    private static final int BPF_ALU_AND_X  = 0x5f; // BPF_ALU64 | BPF_AND | BPF_X
    private static final int BPF_JMP_JNE_K  = 0x55; // BPF_JMP | BPF_JNE | BPF_K
    private static final int BPF_JMP_JEQ_K  = 0x15; // BPF_JMP | BPF_JEQ | BPF_K
    private static final int BPF_EXIT_INSN  = 0x95; // BPF_JMP | BPF_EXIT

    // Device cgroup access bits
    private static final int BPF_DEVCG_ACC_MKNOD = 0x1;
    private static final int BPF_DEVCG_ACC_READ  = 0x2;
    private static final int BPF_DEVCG_ACC_WRITE = 0x4;

    // Device cgroup type bits
    private static final int BPF_DEVCG_DEV_BLOCK = 0x1;
    private static final int BPF_DEVCG_DEV_CHAR  = 0x2;

    private DeviceCgroup() {}

    private static Spec.LinuxDeviceCgroup allow(String type, Long major, Long minor, String access) {
        Spec.LinuxDeviceCgroup r = new Spec.LinuxDeviceCgroup();
        r.allow = true;
        r.type = type;
        r.major = major;
        r.minor = minor;
        r.access = access;
        return r;
    }

    public static void apply(String cgroupPath, List<Spec.LinuxDeviceCgroup> rules) {
        if (rules == null || rules.isEmpty()) return;

        // OCI spec: "The runtime SHOULD allow ... [the default device set]". The
        // default config from runtime-tools (and runc-generated config.json) only
        // lists the catch-all {allow:false, access:"rwm"} and leaves it to the
        // runtime to grant the standard devices on top. We prepend allow rules
        // for the OCI default set so that a "deny everything" rule from the spec
        // doesn't end up blocking /dev/null and friends, which would break sh's
        // own backgrounding (which redirects stdin from /dev/null) and most user
        // workloads. This matches runc's defaultAllowedDevices behaviour.
        java.util.List<Spec.LinuxDeviceCgroup> effective = new java.util.ArrayList<>();
        effective.add(allow("c", 1L, 3L, "rwm")); // /dev/null
        effective.add(allow("c", 1L, 5L, "rwm")); // /dev/zero
        effective.add(allow("c", 1L, 7L, "rwm")); // /dev/full
        effective.add(allow("c", 1L, 8L, "rwm")); // /dev/random
        effective.add(allow("c", 1L, 9L, "rwm")); // /dev/urandom
        effective.add(allow("c", 5L, 0L, "rwm")); // /dev/tty
        effective.add(allow("c", 5L, 1L, "rwm")); // /dev/console
        effective.add(allow("c", 5L, 2L, "rwm")); // /dev/ptmx
        effective.add(allow("c", 136L, null, "rwm")); // pts/* (major 136, any minor)
        effective.addAll(rules);

        byte[] prog = buildProgram(effective);
        Logger.debug("built cgroup_device bpf program, " + (prog.length / 8) + " insns");

        try (Arena arena = Arena.ofConfined()) {
            int progFd = loadProgram(arena, prog);
            if (progFd < 0) {
                Logger.warn("bpf_prog_load failed: " + Libc.strerror(Libc.errno()));
                return;
            }
            try {
                String cgPath = Cgroup.dir(cgroupPath).toString();
                int cgFd = PosixIO.open(arena, cgPath, Constants.O_RDONLY | Constants.O_DIRECTORY, 0);
                if (cgFd < 0) {
                    Logger.warn("open cgroup dir failed: " + Libc.strerror(Libc.errno()));
                    return;
                }
                try {
                    if (attachProgram(arena, cgFd, progFd) != 0) {
                        Logger.warn("bpf_prog_attach failed: " + Libc.strerror(Libc.errno()));
                    } else {
                        Logger.info("device cgroup bpf program attached to " + cgPath);
                    }
                } finally {
                    PosixIO.close(cgFd);
                }
            } finally {
                PosixIO.close(progFd);
            }
        }
    }

    // Package-visible so the unit test suite can pin the emitted bytecode.
    static byte[] buildProgram(List<Spec.LinuxDeviceCgroup> rules) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        // Setup: load ctx fields into R2 (access_type), then derive R3 (access bits),
        // R4 (dev type), R5 (major), R6 (minor).
        emit(out, BPF_LDX_MEM_W, 2, 1, 0, 0);           // R2 = *(u32 *)(R1+0)  access_type
        emit(out, BPF_ALU_MOV_X, 3, 2, 0, 0);           // R3 = R2
        emit(out, BPF_ALU_RSH_K, 3, 0, 0, 16);          // R3 = R3 >> 16        access bits
        emit(out, BPF_ALU_AND_K, 2, 0, 0, 0xFFFF);      // R2 = R2 & 0xFFFF      dev type
        emit(out, BPF_LDX_MEM_W, 5, 1, 4, 0);           // R5 = major
        emit(out, BPF_LDX_MEM_W, 6, 1, 8, 0);           // R6 = minor

        // For each rule: emit branch chain.
        // We use a placeholder "skip distance" and patch later — but since we
        // know each rule emits a fixed-size block we can compute targets in advance.
        // Per-rule block size (max): 8 insns + final 2.
        for (Spec.LinuxDeviceCgroup r : rules) {
            int devType = parseDevType(r.type);
            int accBits = parseAccessBits(r.access);

            // Compute branch length first so we can use BPF_JNE with the right offset.
            // We'll add insns to a sub-stream and then emit them with patched offsets.
            ByteArrayOutputStream sub = new ByteArrayOutputStream();

            if (devType != 0) {
                emit(sub, BPF_JMP_JNE_K, 2, 0, 0 /*patched*/, devType);
            }
            if (accBits != 0) {
                // R7 = R3 & ~accBits ; if R7 != 0 then access requested has bits the
                // rule doesn't grant. Done with: R7 = R3; R7 &= ~accBits; jne 0
                emit(sub, BPF_ALU_MOV_X, 7, 3, 0, 0);
                emit(sub, BPF_ALU_AND_K, 7, 0, 0, ~accBits);
                emit(sub, BPF_JMP_JNE_K, 7, 0, 0, 0);
            }
            if (r.major != null) {
                emit(sub, BPF_JMP_JNE_K, 5, 0, 0, r.major.intValue());
            }
            if (r.minor != null) {
                emit(sub, BPF_JMP_JNE_K, 6, 0, 0, r.minor.intValue());
            }
            // Match: return allow/deny.
            emit(sub, BPF_ALU_MOV_K, 0, 0, 0, r.allow ? 1 : 0);
            emit(sub, BPF_EXIT_INSN, 0, 0, 0, 0);

            byte[] subBytes = sub.toByteArray();
            int totalInsns = subBytes.length / 8;
            // Now patch all BPF_JNE offsets so they jump past the final exit
            // (to fall into the next rule or the default tail).
            patchJumps(subBytes, totalInsns);
            out.writeBytes(subBytes);
        }

        // Default tail: deny.
        emit(out, BPF_ALU_MOV_K, 0, 0, 0, 0);
        emit(out, BPF_EXIT_INSN, 0, 0, 0, 0);

        return out.toByteArray();
    }

    /** For every BPF_JNE in the block, set off = (totalInsns - 1 - position) so it
     *  branches just past the trailing exit. */
    private static void patchJumps(byte[] block, int totalInsns) {
        for (int i = 0; i < totalInsns; i++) {
            int base = i * 8;
            int code = block[base] & 0xff;
            if (code == BPF_JMP_JNE_K) {
                int newOff = totalInsns - 1 - i; // jumps to next-after-exit
                block[base + 2] = (byte) (newOff & 0xff);
                block[base + 3] = (byte) ((newOff >> 8) & 0xff);
            }
        }
    }

    private static int parseDevType(String type) {
        if (type == null || type.isEmpty() || "a".equals(type)) return 0; // 0 = any
        return switch (type) {
            case "c", "u" -> BPF_DEVCG_DEV_CHAR;
            case "b"      -> BPF_DEVCG_DEV_BLOCK;
            default       -> 0;
        };
    }

    private static int parseAccessBits(String access) {
        if (access == null) return 0;
        int b = 0;
        if (access.indexOf('r') >= 0) b |= BPF_DEVCG_ACC_READ;
        if (access.indexOf('w') >= 0) b |= BPF_DEVCG_ACC_WRITE;
        if (access.indexOf('m') >= 0) b |= BPF_DEVCG_ACC_MKNOD;
        return b;
    }

    private static void emit(ByteArrayOutputStream out, int opcode, int dstReg, int srcReg,
                             int off, int imm) {
        byte[] insn = new byte[8];
        ByteBuffer bb = ByteBuffer.wrap(insn).order(ByteOrder.LITTLE_ENDIAN);
        bb.put((byte) opcode);
        bb.put((byte) (((srcReg & 0xF) << 4) | (dstReg & 0xF)));
        bb.putShort((short) off);
        bb.putInt(imm);
        out.writeBytes(insn);
    }

    private static int loadProgram(Arena arena, byte[] prog) {
        // union bpf_attr (size at least 0x80 for old kernels, we round up to 128).
        MemorySegment attr = arena.allocate(128);
        MemorySegment insns = arena.allocate(prog.length);
        insns.copyFrom(MemorySegment.ofArray(prog));
        MemorySegment license = arena.allocateFrom("GPL");
        // Layout of bpf_attr for PROG_LOAD (relevant fields):
        //   u32 prog_type
        //   u32 insn_cnt
        //   u64 insns
        //   u64 license
        //   u32 log_level
        //   u32 log_size
        //   u64 log_buf
        //   u32 kern_version
        //   u32 prog_flags
        attr.set(ValueLayout.JAVA_INT, 0, BPF_PROG_TYPE_CGROUP_DEVICE);
        attr.set(ValueLayout.JAVA_INT, 4, prog.length / 8);
        attr.set(ValueLayout.JAVA_LONG, 8, insns.address());
        attr.set(ValueLayout.JAVA_LONG, 16, license.address());
        long rc = Libc.syscall(bpfNr(), BPF_PROG_LOAD, attr.address(), 128, 0, 0);
        return (int) rc;
    }

    private static int attachProgram(Arena arena, int cgroupFd, int progFd) {
        MemorySegment attr = arena.allocate(64);
        // Layout: u32 target_fd; u32 attach_bpf_fd; u32 attach_type; u32 attach_flags;
        attr.set(ValueLayout.JAVA_INT, 0, cgroupFd);
        attr.set(ValueLayout.JAVA_INT, 4, progFd);
        attr.set(ValueLayout.JAVA_INT, 8, BPF_CGROUP_DEVICE);
        attr.set(ValueLayout.JAVA_INT, 12, 0);
        long rc = Libc.syscall(bpfNr(), BPF_PROG_ATTACH, attr.address(), 64, 0, 0);
        return (int) rc;
    }

    private static long bpfNr() {
        return Constants.isAarch64() ? NR_bpf_aarch64 : NR_bpf_x86_64;
    }
}
