package com.ternbusty.takoyaki.cgroup

import com.ternbusty.takoyaki.logger.Logger
import com.ternbusty.takoyaki.spec.Spec
import com.ternbusty.takoyaki.syscall.Constants
import com.ternbusty.takoyaki.syscall.Libc
import com.ternbusty.takoyaki.syscall.PosixIO
import java.io.ByteArrayOutputStream
import java.lang.foreign.Arena
import java.lang.foreign.MemorySegment
import java.lang.foreign.ValueLayout
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Attach an eBPF program of type BPF_PROG_TYPE_CGROUP_DEVICE to the container's
 * cgroup. The program enforces spec.linux.resources.devices.
 *
 * The generated bytecode iterates over the rule list. Each rule compares the
 * incoming (type, access, major, minor) tuple and short-circuits to return its
 * own allow/deny decision; non-matching rules fall through to the next.
 *
 * BPF input layout (from include/uapi/linux/bpf.h):
 * ```
 *   struct bpf_cgroup_dev_ctx {
 *       __u32 access_type;   // (BPF_DEVCG_ACC_* << 16) | BPF_DEVCG_DEV_*
 *       __u32 major;
 *       __u32 minor;
 *   };
 * ```
 *
 * Output: R0 = 1 to allow, 0 to deny.
 *
 * Reference: runc libcontainer/cgroups/devices/ebpf.go, youki crates/libcgroups
 * cgroup/v2/devices/bpf.rs. Our encoder is a simplified port.
 */
object DeviceCgroup {
    // bpf syscall numbers (same on aarch64 and x86_64 thanks to generic syscalls)

    private const val BPF_PROG_LOAD = 5
    private const val BPF_PROG_ATTACH = 8

    private const val BPF_PROG_TYPE_CGROUP_DEVICE = 15
    private const val BPF_CGROUP_DEVICE = 6

    // BPF instruction opcodes (subset)
    private const val BPF_LDX_MEM_W = 0x61  // BPF_LDX | BPF_MEM | BPF_W
    private const val BPF_ALU_MOV_K = 0xb7  // BPF_ALU64 | BPF_MOV | BPF_K
    private const val BPF_ALU_MOV_X = 0xbf  // BPF_ALU64 | BPF_MOV | BPF_X
    private const val BPF_ALU_RSH_K = 0x77  // BPF_ALU64 | BPF_RSH | BPF_K
    private const val BPF_ALU_AND_K = 0x57  // BPF_ALU64 | BPF_AND | BPF_K
    private const val BPF_ALU_AND_X = 0x5f  // BPF_ALU64 | BPF_AND | BPF_X
    private const val BPF_JMP_JNE_K = 0x55  // BPF_JMP | BPF_JNE | BPF_K
    private const val BPF_JMP_JEQ_K = 0x15  // BPF_JMP | BPF_JEQ | BPF_K
    private const val BPF_EXIT_INSN = 0x95  // BPF_JMP | BPF_EXIT

    // Device cgroup access bits
    private const val BPF_DEVCG_ACC_MKNOD = 0x1
    private const val BPF_DEVCG_ACC_READ = 0x2
    private const val BPF_DEVCG_ACC_WRITE = 0x4

    // Device cgroup type bits
    private const val BPF_DEVCG_DEV_BLOCK = 0x1
    private const val BPF_DEVCG_DEV_CHAR = 0x2

    private fun allow(type: String?, major: Long?, minor: Long?, access: String?): Spec.LinuxDeviceCgroup {
        val r = Spec.LinuxDeviceCgroup()
        r.allow = true
        r.type = type
        r.major = major
        r.minor = minor
        r.access = access
        return r
    }

    fun apply(cgroupPath: String, rules: List<Spec.LinuxDeviceCgroup>?) {
        if (rules.isNullOrEmpty()) return

        // OCI spec: "The runtime SHOULD allow ... [the default device set]". The
        // default config from runtime-tools (and runc-generated config.json) only
        // lists the catch-all {allow:false, access:"rwm"} and leaves it to the
        // runtime to grant the standard devices on top. We prepend allow rules
        // for the OCI default set so that a "deny everything" rule from the spec
        // doesn't end up blocking /dev/null and friends, which would break sh's
        // own backgrounding (which redirects stdin from /dev/null) and most user
        // workloads. This matches runc's defaultAllowedDevices behaviour.
        val effective = mutableListOf<Spec.LinuxDeviceCgroup>()
        effective.add(allow("c", 1L, 3L, "rwm"))    // /dev/null
        effective.add(allow("c", 1L, 5L, "rwm"))    // /dev/zero
        effective.add(allow("c", 1L, 7L, "rwm"))    // /dev/full
        effective.add(allow("c", 1L, 8L, "rwm"))    // /dev/random
        effective.add(allow("c", 1L, 9L, "rwm"))    // /dev/urandom
        effective.add(allow("c", 5L, 0L, "rwm"))    // /dev/tty
        effective.add(allow("c", 5L, 1L, "rwm"))    // /dev/console
        effective.add(allow("c", 5L, 2L, "rwm"))    // /dev/ptmx
        effective.add(allow("c", 136L, null, "rwm")) // pts/* (major 136, any minor)
        effective.addAll(rules)

        val prog = buildProgram(effective)
        Logger.debug("built cgroup_device bpf program, ${prog.size / 8} insns")

        Arena.ofConfined().use { arena ->
            val progFd = loadProgram(arena, prog)
            if (progFd < 0) {
                Logger.warn("bpf_prog_load failed: ${Libc.strerror(Libc.errno())}")
                return
            }
            try {
                val cgPath = Cgroup.dir(cgroupPath).toString()
                val cgFd = PosixIO.open(arena, cgPath, Constants.O_RDONLY or Constants.O_DIRECTORY, 0)
                if (cgFd < 0) {
                    Logger.warn("open cgroup dir failed: ${Libc.strerror(Libc.errno())}")
                    return
                }
                try {
                    if (attachProgram(arena, cgFd, progFd) != 0) {
                        Logger.warn("bpf_prog_attach failed: ${Libc.strerror(Libc.errno())}")
                    } else {
                        Logger.info("device cgroup bpf program attached to $cgPath")
                    }
                } finally {
                    PosixIO.close(cgFd)
                }
            } finally {
                PosixIO.close(progFd)
            }
        }
    }

    // Package-visible so the unit test suite can pin the emitted bytecode.
    internal fun buildProgram(rules: List<Spec.LinuxDeviceCgroup>): ByteArray {
        val out = ByteArrayOutputStream()
        // Setup: load ctx fields into R2 (access_type), then derive R3 (access bits),
        // R4 (dev type), R5 (major), R6 (minor).
        emit(out, BPF_LDX_MEM_W, 2, 1, 0, 0)           // R2 = *(u32 *)(R1+0)  access_type
        emit(out, BPF_ALU_MOV_X, 3, 2, 0, 0)            // R3 = R2
        emit(out, BPF_ALU_RSH_K, 3, 0, 0, 16)           // R3 = R3 >> 16        access bits
        emit(out, BPF_ALU_AND_K, 2, 0, 0, 0xFFFF)       // R2 = R2 & 0xFFFF      dev type
        emit(out, BPF_LDX_MEM_W, 5, 1, 4, 0)            // R5 = major
        emit(out, BPF_LDX_MEM_W, 6, 1, 8, 0)            // R6 = minor

        // runc compat: separate "wildcard" rules (type='a', no major/minor) from
        // specific rules. Specific rules are emitted first. The LAST wildcard
        // rule determines the default tail action. This way, the OCI pattern
        // [{deny all}, {allow b 8:0}] works: the specific allow matches before
        // the default deny.
        var defaultAllow = false // default tail
        val specific = mutableListOf<Spec.LinuxDeviceCgroup>()
        for (r in rules) {
            val rType = r.type
            val isWildcard = (rType == null || rType.isEmpty() || rType == "a") &&
                r.major == null && r.minor == null
            if (isWildcard) {
                defaultAllow = r.allow
            } else {
                specific.add(r)
            }
        }

        // For each specific rule: emit branch chain.
        for (r in specific) {
            val devType = parseDevType(r.type)
            val accBits = parseAccessBits(r.access)

            // Compute branch length first so we can use BPF_JNE with the right offset.
            // We'll add insns to a sub-stream and then emit them with patched offsets.
            val sub = ByteArrayOutputStream()

            if (devType != 0) {
                emit(sub, BPF_JMP_JNE_K, 2, 0, 0 /*patched*/, devType)
            }
            if (accBits != 0) {
                // R7 = R3 & ~accBits ; if R7 != 0 then access requested has bits the
                // rule doesn't grant. Done with: R7 = R3; R7 &= ~accBits; jne 0
                emit(sub, BPF_ALU_MOV_X, 7, 3, 0, 0)
                emit(sub, BPF_ALU_AND_K, 7, 0, 0, accBits.inv())
                emit(sub, BPF_JMP_JNE_K, 7, 0, 0, 0)
            }
            val major = r.major
            if (major != null) {
                emit(sub, BPF_JMP_JNE_K, 5, 0, 0, major.toInt())
            }
            val minor = r.minor
            if (minor != null) {
                emit(sub, BPF_JMP_JNE_K, 6, 0, 0, minor.toInt())
            }
            // Match: return allow/deny.
            emit(sub, BPF_ALU_MOV_K, 0, 0, 0, if (r.allow) 1 else 0)
            emit(sub, BPF_EXIT_INSN, 0, 0, 0, 0)

            val subBytes = sub.toByteArray()
            val totalInsns = subBytes.size / 8
            // Now patch all BPF_JNE offsets so they jump past the final exit
            // (to fall into the next rule or the default tail).
            patchJumps(subBytes, totalInsns)
            out.writeBytes(subBytes)
        }

        // Default tail: use the last wildcard rule's allow/deny decision.
        emit(out, BPF_ALU_MOV_K, 0, 0, 0, if (defaultAllow) 1 else 0)
        emit(out, BPF_EXIT_INSN, 0, 0, 0, 0)

        return out.toByteArray()
    }

    /**
     * For every BPF_JNE in the block, set off = (totalInsns - 1 - position) so it
     * branches just past the trailing exit.
     */
    private fun patchJumps(block: ByteArray, totalInsns: Int) {
        for (i in 0 until totalInsns) {
            val base = i * 8
            val code = block[base].toInt() and 0xff
            if (code == BPF_JMP_JNE_K) {
                val newOff = totalInsns - 1 - i // jumps to next-after-exit
                block[base + 2] = (newOff and 0xff).toByte()
                block[base + 3] = ((newOff shr 8) and 0xff).toByte()
            }
        }
    }

    private fun parseDevType(type: String?): Int {
        if (type == null || type.isEmpty() || type == "a") return 0 // 0 = any
        return when (type) {
            "c", "u" -> BPF_DEVCG_DEV_CHAR
            "b" -> BPF_DEVCG_DEV_BLOCK
            else -> 0
        }
    }

    private fun parseAccessBits(access: String?): Int {
        if (access == null) return 0
        var b = 0
        if ('r' in access) b = b or BPF_DEVCG_ACC_READ
        if ('w' in access) b = b or BPF_DEVCG_ACC_WRITE
        if ('m' in access) b = b or BPF_DEVCG_ACC_MKNOD
        return b
    }

    private fun emit(
        out: ByteArrayOutputStream,
        opcode: Int,
        dstReg: Int,
        srcReg: Int,
        off: Int,
        imm: Int
    ) {
        val insn = ByteArray(8)
        val bb = ByteBuffer.wrap(insn).order(ByteOrder.LITTLE_ENDIAN)
        bb.put(opcode.toByte())
        bb.put((((srcReg and 0xF) shl 4) or (dstReg and 0xF)).toByte())
        bb.putShort(off.toShort())
        bb.putInt(imm)
        out.writeBytes(insn)
    }

    private fun loadProgram(arena: Arena, prog: ByteArray): Int {
        // union bpf_attr (size at least 0x80 for old kernels, we round up to 128).
        val attr = arena.allocate(128)
        val insns = arena.allocate(prog.size.toLong())
        insns.copyFrom(MemorySegment.ofArray(prog))
        val license = arena.allocateFrom("GPL")
        // Verifier log buffer: capture kernel messages on failure.
        val logSize = 16384
        val logBuf = arena.allocate(logSize.toLong())
        // Layout of bpf_attr for PROG_LOAD (relevant fields):
        //   u32 prog_type        offset  0
        //   u32 insn_cnt         offset  4
        //   u64 insns            offset  8
        //   u64 license          offset 16
        //   u32 log_level        offset 24
        //   u32 log_size         offset 28
        //   u64 log_buf          offset 32
        attr.set(ValueLayout.JAVA_INT, 0, BPF_PROG_TYPE_CGROUP_DEVICE)
        attr.set(ValueLayout.JAVA_INT, 4, prog.size / 8)
        attr.set(ValueLayout.JAVA_LONG, 8, insns.address())
        attr.set(ValueLayout.JAVA_LONG, 16, license.address())
        val rc = Libc.syscall(bpfNr(), BPF_PROG_LOAD.toLong(), attr.address(), 128, 0, 0)
        if (rc < 0) {
            // Retry with log_level=1 to get verifier output for diagnosis.
            attr.fill(0.toByte())
            attr.set(ValueLayout.JAVA_INT, 0, BPF_PROG_TYPE_CGROUP_DEVICE)
            attr.set(ValueLayout.JAVA_INT, 4, prog.size / 8)
            attr.set(ValueLayout.JAVA_LONG, 8, insns.address())
            attr.set(ValueLayout.JAVA_LONG, 16, license.address())
            attr.set(ValueLayout.JAVA_INT, 24, 1) // log_level
            attr.set(ValueLayout.JAVA_INT, 28, logSize)
            attr.set(ValueLayout.JAVA_LONG, 32, logBuf.address())
            Libc.syscall(bpfNr(), BPF_PROG_LOAD.toLong(), attr.address(), 128, 0, 0)
            val log = logBuf.getString(0)
            if (log.isNotEmpty()) {
                Logger.warn("bpf verifier: ${log.substring(0, minOf(log.length, 512))}")
            }
        }
        return rc.toInt()
    }

    private fun attachProgram(arena: Arena, cgroupFd: Int, progFd: Int): Int {
        val attr = arena.allocate(64)
        // Layout: u32 target_fd; u32 attach_bpf_fd; u32 attach_type; u32 attach_flags;
        attr.set(ValueLayout.JAVA_INT, 0, cgroupFd)
        attr.set(ValueLayout.JAVA_INT, 4, progFd)
        attr.set(ValueLayout.JAVA_INT, 8, BPF_CGROUP_DEVICE)
        attr.set(ValueLayout.JAVA_INT, 12, 0)
        val rc = Libc.syscall(bpfNr(), BPF_PROG_ATTACH.toLong(), attr.address(), 64, 0, 0)
        return rc.toInt()
    }

    private fun bpfNr(): Long = Constants.NR_bpf
}
