// Generated by jextract

package com.ternbusty.takoyaki.syscall.libseccomp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct scmp_arg_cmp {
 *     unsigned int arg;
 *     enum scmp_compare op;
 *     scmp_datum_t datum_a;
 *     scmp_datum_t datum_b;
 * }
 * }
 */
public class scmp_arg_cmp {

    scmp_arg_cmp() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SeccompH.C_INT.withName("arg"),
        SeccompH.C_INT.withName("op"),
        SeccompH.C_LONG.withName("datum_a"),
        SeccompH.C_LONG.withName("datum_b")
    ).withName("scmp_arg_cmp");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt arg$LAYOUT = (OfInt)$LAYOUT.select(groupElement("arg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int arg
     * }
     */
    public static final OfInt arg$layout() {
        return arg$LAYOUT;
    }

    private static final long arg$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int arg
     * }
     */
    public static final long arg$offset() {
        return arg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int arg
     * }
     */
    public static int arg(MemorySegment struct) {
        return struct.get(arg$LAYOUT, arg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int arg
     * }
     */
    public static void arg(MemorySegment struct, int fieldValue) {
        struct.set(arg$LAYOUT, arg$OFFSET, fieldValue);
    }

    private static final OfInt op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum scmp_compare op
     * }
     */
    public static final OfInt op$layout() {
        return op$LAYOUT;
    }

    private static final long op$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum scmp_compare op
     * }
     */
    public static final long op$offset() {
        return op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum scmp_compare op
     * }
     */
    public static int op(MemorySegment struct) {
        return struct.get(op$LAYOUT, op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum scmp_compare op
     * }
     */
    public static void op(MemorySegment struct, int fieldValue) {
        struct.set(op$LAYOUT, op$OFFSET, fieldValue);
    }

    private static final OfLong datum_a$LAYOUT = (OfLong)$LAYOUT.select(groupElement("datum_a"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_a
     * }
     */
    public static final OfLong datum_a$layout() {
        return datum_a$LAYOUT;
    }

    private static final long datum_a$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_a
     * }
     */
    public static final long datum_a$offset() {
        return datum_a$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_a
     * }
     */
    public static long datum_a(MemorySegment struct) {
        return struct.get(datum_a$LAYOUT, datum_a$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_a
     * }
     */
    public static void datum_a(MemorySegment struct, long fieldValue) {
        struct.set(datum_a$LAYOUT, datum_a$OFFSET, fieldValue);
    }

    private static final OfLong datum_b$LAYOUT = (OfLong)$LAYOUT.select(groupElement("datum_b"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_b
     * }
     */
    public static final OfLong datum_b$layout() {
        return datum_b$LAYOUT;
    }

    private static final long datum_b$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_b
     * }
     */
    public static final long datum_b$offset() {
        return datum_b$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_b
     * }
     */
    public static long datum_b(MemorySegment struct) {
        return struct.get(datum_b$LAYOUT, datum_b$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * scmp_datum_t datum_b
     * }
     */
    public static void datum_b(MemorySegment struct, long fieldValue) {
        struct.set(datum_b$LAYOUT, datum_b$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

