// Generated by jextract

package com.ternbusty.takoyaki.syscall.libseccomp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class SeccompH {

    SeccompH() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("libseccomp.so.2", LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;

    private static class seccomp_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_POINTER,
            SeccompH.C_INT
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * scmp_filter_ctx seccomp_init(uint32_t def_action)
     * }
     */
    public static FunctionDescriptor seccomp_init$descriptor() {
        return seccomp_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * scmp_filter_ctx seccomp_init(uint32_t def_action)
     * }
     */
    public static MethodHandle seccomp_init$handle() {
        return seccomp_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * scmp_filter_ctx seccomp_init(uint32_t def_action)
     * }
     */
    public static MemorySegment seccomp_init$address() {
        return seccomp_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * scmp_filter_ctx seccomp_init(uint32_t def_action)
     * }
     */
    public static MemorySegment seccomp_init(int def_action) {
        var mh$ = seccomp_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_init", def_action);
            }
            return (MemorySegment)mh$.invokeExact(def_action);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_release {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_release");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void seccomp_release(scmp_filter_ctx ctx)
     * }
     */
    public static FunctionDescriptor seccomp_release$descriptor() {
        return seccomp_release.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void seccomp_release(scmp_filter_ctx ctx)
     * }
     */
    public static MethodHandle seccomp_release$handle() {
        return seccomp_release.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void seccomp_release(scmp_filter_ctx ctx)
     * }
     */
    public static MemorySegment seccomp_release$address() {
        return seccomp_release.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void seccomp_release(scmp_filter_ctx ctx)
     * }
     */
    public static void seccomp_release(MemorySegment ctx) {
        var mh$ = seccomp_release.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_release", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_arch_resolve_name {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_arch_resolve_name");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t seccomp_arch_resolve_name(const char *arch_name)
     * }
     */
    public static FunctionDescriptor seccomp_arch_resolve_name$descriptor() {
        return seccomp_arch_resolve_name.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t seccomp_arch_resolve_name(const char *arch_name)
     * }
     */
    public static MethodHandle seccomp_arch_resolve_name$handle() {
        return seccomp_arch_resolve_name.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t seccomp_arch_resolve_name(const char *arch_name)
     * }
     */
    public static MemorySegment seccomp_arch_resolve_name$address() {
        return seccomp_arch_resolve_name.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t seccomp_arch_resolve_name(const char *arch_name)
     * }
     */
    public static int seccomp_arch_resolve_name(MemorySegment arch_name) {
        var mh$ = seccomp_arch_resolve_name.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_arch_resolve_name", arch_name);
            }
            return (int)mh$.invokeExact(arch_name);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_arch_add {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER,
            SeccompH.C_INT
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_arch_add");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_arch_add(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static FunctionDescriptor seccomp_arch_add$descriptor() {
        return seccomp_arch_add.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_arch_add(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static MethodHandle seccomp_arch_add$handle() {
        return seccomp_arch_add.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_arch_add(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static MemorySegment seccomp_arch_add$address() {
        return seccomp_arch_add.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_arch_add(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static int seccomp_arch_add(MemorySegment ctx, int arch_token) {
        var mh$ = seccomp_arch_add.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_arch_add", ctx, arch_token);
            }
            return (int)mh$.invokeExact(ctx, arch_token);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_arch_remove {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER,
            SeccompH.C_INT
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_arch_remove");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_arch_remove(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static FunctionDescriptor seccomp_arch_remove$descriptor() {
        return seccomp_arch_remove.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_arch_remove(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static MethodHandle seccomp_arch_remove$handle() {
        return seccomp_arch_remove.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_arch_remove(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static MemorySegment seccomp_arch_remove$address() {
        return seccomp_arch_remove.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_arch_remove(scmp_filter_ctx ctx, uint32_t arch_token)
     * }
     */
    public static int seccomp_arch_remove(MemorySegment ctx, int arch_token) {
        var mh$ = seccomp_arch_remove.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_arch_remove", ctx, arch_token);
            }
            return (int)mh$.invokeExact(ctx, arch_token);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_load {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_load");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_load(const scmp_filter_ctx ctx)
     * }
     */
    public static FunctionDescriptor seccomp_load$descriptor() {
        return seccomp_load.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_load(const scmp_filter_ctx ctx)
     * }
     */
    public static MethodHandle seccomp_load$handle() {
        return seccomp_load.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_load(const scmp_filter_ctx ctx)
     * }
     */
    public static MemorySegment seccomp_load$address() {
        return seccomp_load.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_load(const scmp_filter_ctx ctx)
     * }
     */
    public static int seccomp_load(MemorySegment ctx) {
        var mh$ = seccomp_load.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_load", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_attr_set {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER,
            SeccompH.C_INT,
            SeccompH.C_INT
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_attr_set");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_attr_set(scmp_filter_ctx ctx, enum scmp_filter_attr attr, uint32_t value)
     * }
     */
    public static FunctionDescriptor seccomp_attr_set$descriptor() {
        return seccomp_attr_set.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_attr_set(scmp_filter_ctx ctx, enum scmp_filter_attr attr, uint32_t value)
     * }
     */
    public static MethodHandle seccomp_attr_set$handle() {
        return seccomp_attr_set.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_attr_set(scmp_filter_ctx ctx, enum scmp_filter_attr attr, uint32_t value)
     * }
     */
    public static MemorySegment seccomp_attr_set$address() {
        return seccomp_attr_set.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_attr_set(scmp_filter_ctx ctx, enum scmp_filter_attr attr, uint32_t value)
     * }
     */
    public static int seccomp_attr_set(MemorySegment ctx, int attr, int value) {
        var mh$ = seccomp_attr_set.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_attr_set", ctx, attr, value);
            }
            return (int)mh$.invokeExact(ctx, attr, value);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_syscall_resolve_name {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_syscall_resolve_name");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_syscall_resolve_name(const char *name)
     * }
     */
    public static FunctionDescriptor seccomp_syscall_resolve_name$descriptor() {
        return seccomp_syscall_resolve_name.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_syscall_resolve_name(const char *name)
     * }
     */
    public static MethodHandle seccomp_syscall_resolve_name$handle() {
        return seccomp_syscall_resolve_name.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_syscall_resolve_name(const char *name)
     * }
     */
    public static MemorySegment seccomp_syscall_resolve_name$address() {
        return seccomp_syscall_resolve_name.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_syscall_resolve_name(const char *name)
     * }
     */
    public static int seccomp_syscall_resolve_name(MemorySegment name) {
        var mh$ = seccomp_syscall_resolve_name.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_syscall_resolve_name", name);
            }
            return (int)mh$.invokeExact(name);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * int seccomp_rule_add(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, ...)
     * }
     */
    public static class seccomp_rule_add {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                SeccompH.C_INT,
                SeccompH.C_POINTER,
                SeccompH.C_INT,
                SeccompH.C_INT,
                SeccompH.C_INT
            );
        private static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_rule_add");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private seccomp_rule_add(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * int seccomp_rule_add(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, ...)
         * }
         */
        public static seccomp_rule_add makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new seccomp_rule_add(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment ctx, int action, int syscall, int arg_cnt, Object... x4) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("seccomp_rule_add", ctx, action, syscall, arg_cnt, x4);
                }
                return (int) spreader.invokeExact(ctx, action, syscall, arg_cnt, x4);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class seccomp_rule_add_array {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER,
            SeccompH.C_INT,
            SeccompH.C_INT,
            SeccompH.C_INT,
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_rule_add_array");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_rule_add_array(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, const struct scmp_arg_cmp *arg_array)
     * }
     */
    public static FunctionDescriptor seccomp_rule_add_array$descriptor() {
        return seccomp_rule_add_array.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_rule_add_array(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, const struct scmp_arg_cmp *arg_array)
     * }
     */
    public static MethodHandle seccomp_rule_add_array$handle() {
        return seccomp_rule_add_array.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_rule_add_array(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, const struct scmp_arg_cmp *arg_array)
     * }
     */
    public static MemorySegment seccomp_rule_add_array$address() {
        return seccomp_rule_add_array.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_rule_add_array(scmp_filter_ctx ctx, uint32_t action, int syscall, unsigned int arg_cnt, const struct scmp_arg_cmp *arg_array)
     * }
     */
    public static int seccomp_rule_add_array(MemorySegment ctx, int action, int syscall, int arg_cnt, MemorySegment arg_array) {
        var mh$ = seccomp_rule_add_array.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_rule_add_array", ctx, action, syscall, arg_cnt, arg_array);
            }
            return (int)mh$.invokeExact(ctx, action, syscall, arg_cnt, arg_array);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class seccomp_notify_fd {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            SeccompH.C_INT,
            SeccompH.C_POINTER
        );

        public static final MemorySegment ADDR = SeccompH.findOrThrow("seccomp_notify_fd");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int seccomp_notify_fd(const scmp_filter_ctx ctx)
     * }
     */
    public static FunctionDescriptor seccomp_notify_fd$descriptor() {
        return seccomp_notify_fd.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int seccomp_notify_fd(const scmp_filter_ctx ctx)
     * }
     */
    public static MethodHandle seccomp_notify_fd$handle() {
        return seccomp_notify_fd.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int seccomp_notify_fd(const scmp_filter_ctx ctx)
     * }
     */
    public static MemorySegment seccomp_notify_fd$address() {
        return seccomp_notify_fd.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int seccomp_notify_fd(const scmp_filter_ctx ctx)
     * }
     */
    public static int seccomp_notify_fd(MemorySegment ctx) {
        var mh$ = seccomp_notify_fd.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("seccomp_notify_fd", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

