#!/usr/bin/env python3
"""cfngen: generate GraalVM Native Image C-interface bindings from C headers.

The "@CFunction side" of jextract. jextract emits Panama FFM code (needs
native-image foreign-downcall registration); this emits GraalVM's C interface
instead, which binds at native link time and needs no registration.

  constants -> `public static final int/long NAME = <value>;`
               The value is read from the header (a probe is compiled and run),
               so it is a plain JVM-safe literal, unlike @CConstant which is a
               native-image-only native method. Header is the source of truth,
               no hand-hardcoding, no arch branch.
  functions -> `@CFunction("name") static native <ret> name(...);`
               Signatures come from `gcc -aux-info`. Pointer and variadic
               functions are skipped unless an explicit --func-sig is given.

Only the scalar (int/long) surface is handled; pointer/struct calls stay on FFM.
"""
import re, subprocess, tempfile, os, argparse, sys

Q = chr(34)
INT = {"int", "unsigned", "unsigned int", "signed int", "__pid_t", "__uid_t",
       "__gid_t", "__mode_t", "uid_t", "gid_t", "pid_t", "mode_t"}
LONG = {"long", "long int", "unsigned long", "unsigned long int", "long long",
        "__off_t", "__off64_t", "off_t", "ssize_t", "size_t", "__ssize_t"}


def jtype(c):
    c = c.strip()
    if c == "void":
        return "void"
    if "*" in c:
        return None
    if c in INT:
        return "int"
    if c in LONG:
        return "long"
    return None


def _src(macros, headers, extra=""):
    return ("".join("#define " + m + "\n" for m in macros)
            + "".join("#include " + h + "\n" for h in headers) + extra)


def prototypes(headers, macros):
    d = tempfile.mkdtemp()
    cf, aux = os.path.join(d, "t.c"), os.path.join(d, "t.aux")
    open(cf, "w").write(_src(macros, headers))
    subprocess.run(["gcc", "-aux-info", aux, "-c", cf, "-o", os.devnull],
                   check=True, stderr=subprocess.DEVNULL)
    return open(aux).read()


def parse_proto(aux, name):
    for line in aux.splitlines():
        if "extern" not in line:
            continue
        m = re.search(r"extern\s+(.+?)\s+" + re.escape(name) + r"\s*\((.*)\)\s*;", line)
        if m:
            return m.group(1), m.group(2)
    return None


def all_func_names(aux):
    """Every function declared by the included headers, in declaration order."""
    names, seen = [], set()
    for line in aux.splitlines():
        if "extern" not in line:
            continue
        m = re.search(r"extern\s+.+?\s+\**(\w+)\s*\(", line)
        if m and m.group(1) not in seen:
            seen.add(m.group(1))
            names.append(m.group(1))
    return names


def const_value(headers, macros, macro):
    """Compile+run a one-off probe; return (value, sizeof) or None if undefined."""
    d = tempfile.mkdtemp()
    cf, exe = os.path.join(d, "p.c"), os.path.join(d, "p")
    body = ("#include <stdio.h>\nint main(){ printf(%s%%lld|%%zu%s,"
            "(long long)(%s),sizeof(%s)); return 0; }\n" % (Q, Q, macro, macro))
    open(cf, "w").write(_src(macros, headers, body))
    if subprocess.run(["gcc", cf, "-o", exe],
                      stderr=subprocess.DEVNULL).returncode != 0:
        return None
    out = subprocess.run([exe], capture_output=True, text=True).stdout.strip()
    v, sz = out.split("|")
    return int(v), int(sz)


def parse_override(s):  # "prctl=int:int,long,long,long,long"
    name, rest = s.split("=", 1)
    ret, args = rest.split(":", 1)
    return name, (ret, [a.strip() for a in args.split(",") if a.strip()])


def parse_const(s):  # "NR_capset=SYS_capset" or "PR_SET_KEEPCAPS"
    return tuple(s.split("=", 1)) if "=" in s else (s, s)


def emit(pkg, cls, headers, macros, funcs, consts, overrides):
    aux = prototypes(headers, macros)
    skipped = []
    L = ["package " + pkg + ";", "",
         "import org.graalvm.nativeimage.c.CContext;",
         "import org.graalvm.nativeimage.c.function.CFunction;",
         "import java.util.List;", "",
         "// GENERATED by tools/cfngen.py from C headers. Do not edit.",
         "public final class " + cls + " {", "    private " + cls + "() {}", ""]
    for java_name, macro in consts:
        cv = const_value(headers, macros, macro)
        if cv is None:
            skipped.append((java_name, "constant " + macro + " undefined"))
            continue
        val, sz = cv
        jt, suf = ("long", "L") if sz > 4 else ("int", "")
        L.append("    public static final " + jt + " " + java_name + " = " + str(val) + suf + ";")
    L += ["",
          "    static final class Directives implements CContext.Directives {",
          "        @Override public List<String> getMacroDefinitions() { return List.of("
          + ", ".join(Q + m.split()[0] + Q for m in macros) + "); }",
          "        @Override public List<String> getHeaderFiles() { return List.of("
          + ", ".join(Q + h + Q for h in headers) + "); }",
          "    }", "",
          "    @CContext(Directives.class)",
          "    public static final class Posix {", "        private Posix() {}"]
    # No explicit --function list => bind EVERY scalar function the headers
    # declare (jextract/cinterop style). New libc calls then need no cfngen
    # change: the binding already exists. Explicit --function narrows the set.
    explicit = set(funcs)
    fnlist = list(funcs) if funcs else all_func_names(aux)
    for n in overrides:
        if n not in fnlist:
            fnlist.append(n)
    for fn in fnlist:
        if fn in overrides:
            ret, args = overrides[fn]
            params = ", ".join(args[i] + " a" + str(i) for i in range(len(args)))
            L.append("        @CFunction(" + Q + fn + Q + ") public static native "
                     + ret + " " + fn + "(" + params + ");")
            continue
        reason, sig = None, None
        p = parse_proto(aux, fn)
        if not p:
            reason = "prototype not found"
        else:
            ret, args = p
            jret = jtype(ret)
            al = [] if args.strip() in ("void", "") else [a.strip() for a in args.split(",")]
            ja = [jtype(a) for a in al]
            if jret is None:
                reason = "unsupported return " + ret
            elif "..." in args:
                reason = "variadic (use --func-sig)"
            elif any(x is None for x in ja):
                reason = "unsupported arg in (" + args + ")"
            else:
                sig = (jret, ja)
        if sig is None:
            # In all-functions mode, silently skip the (many) pointer/variadic
            # libc functions; only report misses that were explicitly requested.
            if fn in explicit:
                skipped.append((fn, reason))
            continue
        jret, ja = sig
        params = ", ".join(ja[i] + " a" + str(i) for i in range(len(ja)))
        L.append("        @CFunction(" + Q + fn + Q + ") public static native "
                 + jret + " " + fn + "(" + params + ");")
    L += ["    }", "}"]
    return "\n".join(L), skipped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--package", required=True)
    ap.add_argument("--class-name", required=True)
    ap.add_argument("--header", action="append", default=[])
    ap.add_argument("--macro", action="append", default=[])
    ap.add_argument("--function", action="append", default=[])
    ap.add_argument("--constant", action="append", default=[])
    ap.add_argument("--func-sig", action="append", default=[])
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    ov = dict(parse_override(s) for s in a.func_sig)
    consts = [parse_const(s) for s in a.constant]
    code, skipped = emit(a.package, a.class_name, a.header, a.macro,
                         a.function, consts, ov)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, "w").write(code + "\n")
    print("cfngen: wrote " + a.out)
    for name, why in skipped:
        print("cfngen: SKIP " + name + ": " + why, file=sys.stderr)


if __name__ == "__main__":
    main()
